### ISSUE TITLE
memory error during training

### ISSUE THREAD

**Issue by michaelcapizzi** [NervanaSystems/deepspeech#10]
I am trying to train my own model (using the default hyperparameters in `train.py`) with the `Fisher English` dataset (which is rather large), and I'm running into memory errors during training:

```Traceback (most recent call last):
  File "train.py", line 425, in <module>
    cost=cost, callbacks=callbacks)
  File "/srv/neon/neon/models/model.py", line 174, in fit
    self.initialize(dataset, cost)
  File "/srv/neon/neon/models/model.py", line 128, in initialize
    self.layers.allocate()
  File "/srv/neon/neon/layers/container.py", line 295, in allocate
    l.allocate()
  File "/srv/neon/neon/layers/recurrent.py", line 1466, in allocate
    self.h_ff_buffer = self.be.zeros_like(self.outputs)
  File "/srv/neon/neon/backends/nervanagpu.py", line 1432, in zeros_like
    rounding=self.round_mode)._assign(0)
  File "/srv/neon/neon/backends/nervanagpu.py", line 146, in __init__
    self.gpudata = allocator(self.nbytes)
pycuda._driver.MemoryError: cuMemAlloc failed: out of memory
```

This is with a batch size of `32`, and if I try to go any smaller I get the expected error about dimensionality:

```
Traceback (most recent call last):
  File "train.py", line 425, in <module>
    cost=cost, callbacks=callbacks)
  File "/srv/neon/neon/models/model.py", line 174, in fit
    self.initialize(dataset, cost)
  File "/srv/neon/neon/models/model.py", line 121, in initialize
    prev_input = self.layers.configure(prev_input)
  File "/srv/neon/neon/layers/container.py", line 275, in configure
    in_obj = l.configure(in_obj)
  File "/srv/neon/neon/layers/layer.py", line 773, in configure
    self.nglayer = self.be.conv_layer(self.be.default_dtype, **self.convparams)
  File "/srv/neon/neon/backends/nervanagpu.py", line 1943, in conv_layer
    dil_d, dil_h, dil_w)
  File "/srv/neon/neon/backends/layer_gpu.py", line 422, in __init__
    self.fprop_kernels = convolution.FpropCuda(*args)
  File "/srv/neon/neon/backends/convolution.py", line 136, in __init__
    assert N % 32 == 0, "N dim must be multiple of 32"
AssertionError: N dim must be multiple of 32
```

I'm running on an `aws` instance: `g2.8xlarge`.

I'm not familiar with `cuda` or `memory allocation` in general, but I'd like to find a workaround that does *not* require me to reduce the size of my training data.  

What are my options?  

Thanks in advance.

**Comment by michaelcapizzi** [comment]
Follow up:

I've reduced the number of audio samples to 10 and still getting errors, so I'm thinking the dimension that is actually causing the memory issues revolves around one of these:

```
max_duration: 40.25
max_tscrpt_len: 409
```

My guess is that the longest audio sample of `40.25 seconds` is the culprit.

**Comment by Neuroschemata** [comment]
I believe the g2.8xlarge AWS instances have 4GB of memory per GPU. With max_duration set to 40.25 seconds, the model's footprint is about 9.3GB. With 4GB as a limit, you would need to set the max_duration to 14.5 seconds or less. Even with the depth of the RNN stack reduced to 3, a max_duration of 40.25 seconds requires 4.3GB of memory.

**Comment by michaelcapizzi** [comment]
Thanks @Neuroschemata.  I wasn't even aware of how to read the "footprint" as you put it.  Your reference is very helpful.  I'm currently rerunning my data with a threshold of utterance length.  

I assume that the duration of the audio is a much more significant dimension than the number of characters in the transcript.  And presumably, capping the audio length will also indirectly cap the transcript length.

**Comment by Neuroschemata** [comment]
FWIW, I simply used the nvidia-smi command to probe the GPU memory usage when loading models to figure out what happens with very long utterance lengths. 

You are correct in assuming that the length of the transcripts plays a marginal role. In the dataloader, the audio samples and the transcripts are handled independently, so capping the length of the audio will not "truncate" the transcripts. If you choose to cap the audio lengths, you should probably figure out a "reasonable" way of capping the transcript lengths as well. 

My first recommendation would be that you avoid capping the lengths at all, and instead use a smaller minibatch size. If you leave all the other model parameters unchanged, a batch size of 4 will easily accommodate the lengthy audio samples. However, you should keep in mind that the longer the audio samples, the longer it will take for your model to converge. I hope that helps.

**Comment by michaelcapizzi** [comment]
Thanks @Neuroschemata for taking the time to respond.

One quick question though.  How can I change the batch size?  When I tried to set it less than `32` in the `train.py` I got the following error:

```
Traceback (most recent call last):
  File "train.py", line 425, in <module>
    cost=cost, callbacks=callbacks)
  File "/srv/neon/neon/models/model.py", line 174, in fit
    self.initialize(dataset, cost)
  File "/srv/neon/neon/models/model.py", line 121, in initialize
    prev_input = self.layers.configure(prev_input)
  File "/srv/neon/neon/layers/container.py", line 275, in configure
    in_obj = l.configure(in_obj)
  File "/srv/neon/neon/layers/layer.py", line 773, in configure
    self.nglayer = self.be.conv_layer(self.be.default_dtype, **self.convparams)
  File "/srv/neon/neon/backends/nervanagpu.py", line 1943, in conv_layer
    dil_d, dil_h, dil_w)
  File "/srv/neon/neon/backends/layer_gpu.py", line 422, in __init__
    self.fprop_kernels = convolution.FpropCuda(*args)
  File "/srv/neon/neon/backends/convolution.py", line 136, in __init__
    assert N % 32 == 0, "N dim must be multiple of 32"
AssertionError: N dim must be multiple of 32
```

I assumed this would require me to dig into the `data loader` code but didn't have the time to do so yet.

**Comment by Neuroschemata** [comment]
Unfortunately, the suggestion I made regarding reducing batch size to 4 is not supported on Kepler cards (used in the AWS instances). So, with 4GB of memory, you are limited to audio lengths of 14.5 seconds or less. Smaller batch sizes are supported on Maxwell GPUs.

**Comment by saurabhvyas** [comment]
Okay , so in evaluate.py file I modified batch size to 4 from default and then It started evaluating , I have got 
cer = 0.135313778528
Can anyone comment if this is normal and after this how should I evaluate from a single .wav file ?
