### ISSUE TITLE
i find the problem about the conv layer input shape and outshape

### ISSUE THREAD

**Issue by ghost** [NervanaSystems/deepspeech#11]
i use pdf find: the conv layer,inputshape is (1,13,2998),and output is (1152,1,1000)

the input shape is one vedio ,but the batchsize is 32,,,
Is it a convolution of a vedio do　frop?????

**Comment by ghost** [comment]
i use pdb find: the conv layer,inputshape is (1,13,2998),and output is (1152,1,1000)

the input shape is one vedio ,but the batchsize is 32,,,
Is it a convolution of a vedio do　frop?????

**Comment by tyler-nervana** [comment]
I've answered this question in #9 so let's carry on any discussion there.
