### ISSUE TITLE
what is BIRNN input and output in deepspeech2?

### ISSUE THREAD

**Issue by ghost** [NervanaSystems/deepspeech#12]
what is BIRNN input and output in deepspeech2?

**Comment by tyler-nervana** [comment]
We utilize the `DeepBiRNN` layer container implemented in neon: https://neon.nervanasys.com/index.html/generated/neon.layers.recurrent.DeepBiRNN.html. Each layer concatenates the forward and backward RNN activations and sends them on to the next layer. The input to the stack is the output of the initial 1D convolution layer. We detail this a bit more in our [blog post](https://www.nervanasys.com/end-end-speech-recognition-neon/) on the model.

I hope this helps!
