### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by pankaj2701** [NervanaSystems/deepspeech#13]
I am trying to train a model using the librispeech recipe, just to understand the flow. WHat should be the batch size -b.
For any value of batch size I am getting the following error

  pycuda._driver.MemoryError: cuMemAlloc failed: out of memory

I am using a a core i7 laptop with 16 GB DDR4 and a NVIDIA GTX 960M GPU with 4 GB GDDR5. Would it be possible to train the model on this machine.

Regards
Pankaj

**Comment by tyler-nervana** [comment]
We are still working out what the best solution is to this. See #10 for the same issue.
