### ISSUE TITLE
`neon` WARNING at end of each `train` epoch and `nan` cost

### ISSUE THREAD

**Issue by michaelcapizzi** [NervanaSystems/deepspeech#14]
I'm trying to train a model using my own data.  I have set up the files and `manifest` properly (I think), but I am getting the following `WARNING` at the end of each epoch:

```
2017-02-08 16:16:53,074 - neon - WARNING - can't describe argument 'max_label_len' to <ctc.CTC object at 0x7f61f7d80f90>
2017-02-08 16:16:53,074 - neon - WARNING - can't describe argument 'blank' to <ctc.CTC object at 0x7f61f7d80f90>
```

When I look at the `neon` code, I can see this warning is logged whenever the argument is not in the `__dict__` of the `NervanaObject`.  See [here](https://github.com/NervanaSystems/neon/blob/4fb5ff6a4b622facfb07b28da94b992159aac8cc/neon/__init__.py#L168).  But I can't say I understand what I'm doing wrong as I don't have `max_label_len` nor `blank` as variables anywhere in my `train.py` script.

The training completes (as this is just a `WARNING`), however, I quickly reach `nan` cost.  I assume that this `WARNING` does not contribute to the `nan` cost issue, but before I dig deeply into figuring out where the neural network issue is (I understand that the calculation of cost is "shipped" off to `CTC`), I wanted to eliminate any "lower hanging fruit."

So.....

1) Why am I getting this `WARNING`?
2) Is this at all contributing to my cost issues?
extra credit) If not #2, any suggestions on where to start trying to debug my cost error?

Thanks, as always, in advance.
-M

**Comment by Neuroschemata** [comment]
You are correct in suspecting that the warning and the nan costs are unrelated. The warnings are coming from the mechanism used to serialize the model (e.g. saving the state of the model at each epoch to enable a user to resume training from a saved "checkpoint"). You can safely ignore the warnings for now (we will work to address resolving the warnings). 

As for where the nan values are coming from, I would suggest first looking at the values assigned to your transcripts. For example, if you are using the alphabet A through Z, plus the blank symbol, you should make sure that your transcripts only include positive integers <=26. More than likely, the issue is coming from a "mismatch" between your actual data and what neon expects. I hope that helps.

**Comment by michaelcapizzi** [comment]
That is helpful @Neuroschemata.  But now I'm a bit confused.

> As for where the nan values are coming from, I would suggest first looking at the values assigned to your transcripts. For example, if you are using the alphabet A through Z, plus the blank symbol, you should make sure that your transcripts only include positive integers <=26. 

This leads me to believe that my `transcript` files should be a sequence of integers?

So if my target line is `A B C D`, does that mean that the transcript file that I point to in my `manifest` file should be `1 2 3 4`?

I'm sorry if that's obvious and I missed it, but I was under the impression that each `transcript.txt` file was simply the "words".  

So either (1) I was mistaken and I need to provide `deepspeech` with `transcript.txt` files of indices or (2) the mapping from character to index is done during the `DataLoader` process.

I have started to do some initial debugging of what that `DataLoader` holds, but again I thought I'd check in before spending too much time figuring it out.

Any guidance/confirmation is, again, appreciated.

**Comment by michaelcapizzi** [comment]
@Neuroschemata I realize this has shifted into another "issue".  If you'd prefer, I'll happily open a new issue for this conversation.  Just let me know.

**Comment by tyler-nervana** [comment]
The mapping from character to index is done in the dataloader process. It uses the `alphabet` key that you provide to the `transcription` configuration. Check to see if your transcripts contain any characters that are not in the alphabet.

**Comment by michaelcapizzi** [comment]
Thank you @tyler-nervana.  I assumed that was the case and I'm checking my `transcript` file right now.  I will `close` this issue.

**Comment by tyler-nervana** [comment]
Great. If you do find an issue with the dataloader, could you post it here: https://github.com/NervanaSystems/aeon?
