### ISSUE TITLE
Deepbirnn layer split_input parameter

### ISSUE THREAD

**Issue by ghost** [NervanaSystems/deepspeech#16]
neon Deepbirnn layer split_input parameter？
When the second layer rnn time, split_input parameter is set to true ,,, then forward with the former 1152 parameters, backward spread with 1152 parameters ,,, Why is this set?

**Comment by ghost** [comment]
if i want use tensorlayer to achieve ,what should i do?

**Comment by tyler-nervana** [comment]
The `split_input` parameter allows one to stack multiple forward RNNs and multiple backward RNNs before eventually combining their outputs at the top layer. It basically keeps the outputs from each layer separate as they are propagated up through next RNN layer. Could you clarify what you mean by "tensorlayer"?
