### ISSUE TITLE
phoneme classification

### ISSUE THREAD

**Issue by pankaj2701** [NervanaSystems/deepspeech#18]
I am trying to use deepspeech for phoneme classification.
I am not able to figure out how to specify the phoneme set.
For character recognition the alphabet is a set of unique characters
but not in case of phonemes. I tried to specify the symbols for phonemes as a list
but that gives an error

aeon.dataloader.LoaderRuntimeError: error in loader: type must be string, but is array

Any suggestion?

**Comment by rkimballn1** [comment]
That error message is from the parsing of config data. Can I see how you are configuring the dataloader?

**Comment by pankaj2701** [comment]
I have done the following change in train.py.
I have specified the alphabet as
alphabet = ["SIL","AA","AE","AH","AO","AW","AY","B","CH","D","DH","EH",
            "ER","EY","F","G","HH","IH","IY","JH","K","L","M","N","NG",
            "OW","OY","P","R","S","SH","T","TH","UH","UW","V","W","Z","ZH"]

From the error message I guess the alphabet should be specified as a string of unique characters. 
But then how to specify phoneme set as a string, as it contains repetition of characters.

**Comment by tyler-nervana** [comment]
It looks like you have found a workaround for this issue (#32). That should work fine as a stopgap until unicode support is added to aeon, the dataloader we use in this repo.
