### ISSUE TITLE
Can I know more details about weighted finite state transducers (WFSTs)

### ISSUE THREAD

**Issue by hhbyyh** [NervanaSystems/deepspeech#22]
The default argmax decoder does not have a good performance. Can you please share more information about the  weighted finite state transducers (WFSTs)? Like which version or is there a trained model that can be used. Thanks.

**Comment by tyler-nervana** [comment]
We don't have any code to share at the moment. However, much of our process adapts the decoders from [EESEN](https://github.com/srvk/eesen), which is derived from [kaldi](https://github.com/kaldi-asr/kaldi). The WFST creation and decoding should follow what is described in this [script](https://github.com/srvk/eesen/blob/master/asr_egs/wsj/run_ctc_char.sh). The output from the deepspeech 2 model in this repo can be dumped to a ".ark" file using [kaldi-io-for-python](https://github.com/vesis84/kaldi-io-for-python).

I hope this helps!

**Comment by hhbyyh** [comment]
Thanks a lot @tyler-nervana. Have you tried other toolkit like [OpenFst](http://openfst.org/twiki/bin/view/FST/WebHome), not sure if it's recommended.

**Comment by tyler-nervana** [comment]
That works for the fst creation, though it is slower than using Kaldi's customized versions for creating large composed FSTs. As a starting point, it is easiest to use EESEN's fst creation pipeline. If you have a more customized decoding task in mind, or just want to learn more about FST decoding, building the FSTs yourself with OpenFST's python bindings can be really useful.
