### ISSUE TITLE
Language Model

### ISSUE THREAD

**Issue by nsomaru** [NervanaSystems/deepspeech#25]
According to your [blog post](https://www.nervanasys.com/end-end-speech-recognition-neon/), it looks like you were able to achieve 8.4% WER using a trigram language model. However, it doesn't seem like you have integrated that language model into this repo. 

Could you describe how this is done or share that with us?

**Comment by tyler-nervana** [comment]
I talked about this a bit in #22, but if you have any questions beyond that, I'd be happy to try and answer them. At the moment we don't really have any code that we are prepared to share, though.
