### ISSUE TITLE
no handler for detected file type `flac'

### ISSUE THREAD

**Issue by striki70** [NervanaSystems/deepspeech#27]
I am trying to make this work. Unfortunately, with evaluate.py and train.py I'm receiving the following errors:

2017-05-08 16:51:52,109 - neon.util.argparser - WARNING - No schedule given for model serialization, using default 1
2017-05-08 16:51:52,505 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
formats: no handler for detected file type `flac'
formats: no handler for detected file type `flac'
formats: no handler for detected file type `flac'
formats: no handler for detected file type `flac'formats: no handler for detected file type `flac'formats: no handler for detected file type `flac'

formats: no handler for detected file type `flac'
Unable to readUnable to readUnable to readUnable to readUnable to readUnable to readdecode_thread_pool exception: decode_thread_pool exception: number of frames is negativenumber of frames is negative
decode_thread_pool exception:
decode_thread_pool exception: number of frames is negative
number of frames is negative
decode_thread_pool exception: number of frames is negative
decode_thread_pool exception: number of frames is negative
formats: no handler for detected file type `flac'
Unable to readdecode_thread_pool exception: number of frames is negative
Unable to readdecode_thread_pool exception: number of frames is negative
Segmentation fault (core dumped)

Any hint how to deal with flac files?

**Comment by tyler-nervana** [comment]
Hmm, we definitely expect flac decoding to work properly (Librispeech uses flac encoding, after all).  Could you make sure you have all of the required dependencies for aeon and try reinstalling it (https://aeon.nervanasys.com/index.html/getting_started.html)?

**Comment by striki70** [comment]
I installed required dependencies, and still, again the same issue.
Is there a way that I use wav files as input for training and evaluation?

**Comment by tyler-nervana** [comment]
Yes, you can definitely just convert the files to wav for training and evaluation. The `sox` command line utility should make pretty quick work of that. Then just update your manifest file to reference the wav files and you should be good to go.
