### ISSUE TITLE
Read this for Audio file outside Librespeech

### ISSUE THREAD

**Issue by rshravan** [NervanaSystems/deepspeech#3]
Hi, 

If you are going to use external data for validation (not in Librespeech) don't forget to change it to 16 bit, mono and into 16KHz FLAC format. Audacity is best for this conversion (ffmpeg conversion didn't work with -f s16be or -f s16le). Not doing this will either throw an error (audio must be signed short) or just product "qqqqqqqqqqq" (the TV White noise) or some other jibberish (specially if it's not 16KHz). 

LIbrespeech data is mostly British/Western English, so of course, the trained model won't work best on other accents.

**Comment by saurabhvyas** [comment]
Can you tell me How I can evaluate my pretrained model with a .wav file with above specifications ?
