### ISSUE TITLE
Error when evaluate a new trained model

### ISSUE THREAD

**Issue by duongquangduc** [NervanaSystems/deepspeech#30]
Hi expert,
I am facing an issue when evaluate a new trained model. Could you please suggest?
Here is the details:
neon.util.argparser - ERROR - No read access for model file root/deepspeech/model_output.pkl
None
Traceback (most recent call last):
  File "evaluate.py", line 47, in <module>
    args = parser.parse_args()
  File "/neon/neon/util/argparser.py", line 345, in parse_args
    raise IOError(err_msg)
IOError: No read access for model file root/deepspeech/model_output.pkl

![image](https://cloud.githubusercontent.com/assets/28558875/26760570/b4bbc39e-4946-11e7-843f-1209b6c0b909.png)

**Comment by tyler-nervana** [comment]
Hi, it looks like you just forgot a "/" in "/root". That's a bit of a strange error message, though, so let us know  if that is not the case.

**Comment by duongquangduc** [comment]
I tried again with and without "/" but still there is the same issue. 
![image](https://user-images.githubusercontent.com/28558875/26862464-a1386b70-4b75-11e7-97f5-82ba23540ac0.png)
and 
![image](https://user-images.githubusercontent.com/28558875/26862481-c916056c-4b75-11e7-99f8-80e886861585.png)

**Comment by duongquangduc** [comment]
Hi,
Yes, I may miss the "/". I added and executed the statement again but now it comes another error.
Could you please take a look into the output message?
Statement:
~/deepspeech/speech# python evaluate.py --manifest val:/root/deepspeech/librispeech/train-clean-100/val-manifest.csv --model_file /root/deepspeech/model_output.pkl
Output:
2017-06-07 08:17:34,109 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
Traceback (most recent call last):
  File "evaluate.py", line 95, in <module>
    eval_set = DataLoader(backend=be, config=eval_cfg_dict)
  File "/neon/.venv2/local/lib/python2.7/site-packages/aeon/dataloader.py", line 56, in __init__
    self._load_library()
  File "/neon/.venv2/local/lib/python2.7/site-packages/aeon/dataloader.py", line 83, in _load_library
    self.loaderlib = ct.cdll.LoadLibrary(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so.1: cannot open shared object file: No such file or directory

Screenshot:
![image](https://user-images.githubusercontent.com/28558875/26869142-8cc9b926-4b95-11e7-97e3-a14481addb7f.png)

**Comment by duongquangduc** [comment]
Yes, it may be the cause. I changed some settings, added the "/", and now I am able to run the statement to verify the model. There are two warning messages though it can still run through.
I will let me you know if there is any issue once I finish verifying the model and printing out the text corresponding to the audio file.
![image](https://user-images.githubusercontent.com/28558875/26874400-a248ddd8-4ba7-11e7-847c-b63edd9ff7dc.png)


In the meantime, I have a question regarding the evaluation step. In case I want to verify any audio file, which format of the audio file can be applied for this framework? Do I need to preprocess a given audio file (for example, .mp3, .wav...)?


Thank you for the support!
Duc

**Comment by tyler-nervana** [comment]
Great to hear. The warning messages won't cause any real issues. You should be able to use any audio file that [libsox](http://sox.sourceforge.net/Main/HomePage) can support. If you have any issues with this, you can post on the issue tracker for [aeon](https://github.com/NervanaSystems/aeon/issues).

**Comment by duongquangduc** [comment]
Hi,
I am able to evaluate the sample data now. Thank you for your kind support!
I will continue working on this framework. So, I hope to receive more help from you.
Kind regards,
Duc
