### ISSUE TITLE
Error while using pre-trained weights in evaluate.py

### ISSUE THREAD

**Issue by anindyasarkarIITH** [NervanaSystems/deepspeech#33]
We are getting the following issue : 

OSError:  /deep_speech/neon/.venv2/lib/python2.7/site-packages/aeon_lib.so: undefined symbol: _ZTVN2cv11_InputArrayE

**Comment by tyler-nervana** [comment]
Hi, that's an issue with the aeon dataloader. We are experiencing it ourselves internally and will get back to you as soon as we understand what's causing it. Thanks for alerting us!

**Comment by tyler-nervana** [comment]
Thanks for alerting us to this. It's an issue with linking to OpenCV. If you do not already have opencv installed on your system, it is required. If you do have it installed, could you try adding the directory that contains `opencv.pc` to your `PKG_CONFIG_PATH` environment variable?
