### ISSUE TITLE
'nan' cost

### ISSUE THREAD

**Issue by basant-kumar** [NervanaSystems/deepspeech#38]
hi, I'm getting nan cost after resuming the training for the pre-trained model (librispeech_16_epochs.prm).
the cost becomes **nan** after 16/17 epoch and the testing results (after each epoch) are null.

OS: Ubuntu 16.04
GPU: Nvidia Titan-X Pascal (12GB RAM)
Neon: version 1.9.0

**Comment by Neuroschemata** [comment]
This is a duplicate of #37.
