### ISSUE TITLE
Wrong arguments error in utils.py

### ISSUE THREAD

**Issue by w4-kang** [NervanaSystems/deepspeech#41]
Hi, I got Error "TypeError: write() argument must be str, not bytes" in utils.py
I'm not familiar with python, but I guess it could be python2 and 3 compatible problem. (I run evaluate.py with python 3.6.1 (anaconda))
Above error comes from 
utils.py > `get_wer(...)` > `sys.stdout.write(progress_string.encode("utf-8"))` [line 78].
When I modify `progress_string.encode("utf-8")` to just `progress_string`, it works well (but I couldn't test it with python 2 because my environment allows python3 only.)

**Comment by tyler-nervana** [comment]
Thanks for notifying us on this. You're right that this is a [python 3 issue](https://stackoverflow.com/questions/21689365/python-3-typeerror-must-be-str-not-bytes-with-sys-stdout-write).
