### ISSUE TITLE
Can't training on multi gpu devices.

### ISSUE THREAD

**Issue by w4-kang** [NervanaSystems/deepspeech#44]
Hi, I have a environment which has multiple gpu devices (1080ti 2way).
So, I tried run training with `-m 2` options. But it uses only first gpu devices.
Even I set parameter `max_devices` with 2 to `gen_backend()` statement, it still uses only 1 devices. (with increased batch_size, it throws memory error instead use second device)
For your information my environment settings are below:
os: ubuntu 16.04
cuda version: 8.0
gpu devices: 1080ti 2way.
cpu device: intel skylake i7.
virtual env: anaconda (python3).

**Comment by gardenia22** [comment]
multiple gpu is not available in this open source version. see issue #5.

**Comment by w4-kang** [comment]
Oops.. I didn't realize that, Thanks.
