### ISSUE TITLE
"ImportError: No module named neon.backends" 

### ISSUE THREAD

**Issue by rsbhat78** [NervanaSystems/deepspeech#47]
(.venv2) bharagha@ubuntu-server:~/workload$ python deepspeech/speech/train.py --mainfest train:librispeech/train-clean-100/train-manifest.csv --manifest val:librispeech/train-clean-100/val-manifest.csv -e 4 -z 3 -s deepspeech/model_output.pkl -b mkl
Traceback (most recent call last):
  File "deepspeech/speech/train.py", line 24, in <module>
    from neon.backends import gen_backend
ImportError: No module named neon.backends

I am trying to train using the librispeech samples. Ran into the above issue. Neon is installed as per the instructions on webpage. Kindly advise.

**Comment by rsbhat78** [comment]
I have been able to resolve the above issue. However, running into another ImportError issue with respect to the aeon.dataloader. This is happening though Aeon is installed fine. As a proof, I am able to run mnist example without any issue. Any hints will be very useful.

**Comment by tyler-nervana** [comment]
Could you post the stacktrace on the aeon error? Aeon is mostly used for large datasets like librispeech and imagenet, so the mnist example doesn't use it.

**Comment by rsbhat78** [comment]
(.venv2) bharagha@ubuntu-server:~/common/neon$ python ../deepspeech/speech/train.py --mainfest train:../librispeech/train-clean-100/train-manifest.csv --manifest val:../librispeech/train-clean-100/val-manifest.csv -e 4 -z 3 -s ../deepspeech/model_output.pkl -b mkl
Traceback (most recent call last):
  File "../deepspeech/speech/train.py", line 23, in <module>
    from aeon.dataloader import DataLoader
ImportError: No module named aeon.dataloader

Attached the

**Comment by tyler-nervana** [comment]
Try re-installing aeon from within your neon virtual environment ([see here](http://aeon.nervanasys.com/index.html/getting_started.html#installation)). It should just require these three steps:
```
git clone https://github.com/NervanaSystems/aeon.git
cd aeon
python setup.py install
```

**Comment by rsbhat78** [comment]
Thanks. It helped.

**Comment by rsbhat78** [comment]
One more question. I am trying to execute the following command:
_python ../../deepspeech/speech/train.py --manifest train:/home/bharagha/common/librispeech/train-clean-100/train-manifest.csv --manifest val:/home/bharagha/common/librispeech/train-clean-100/val-manifest.csv -e 2 -z 3 -s ../deepspeech/model_output.pkl -b mkl_

I get a segmentation fault with the following message:

2017-08-07 19:04:35,828 - neon.util.argparser - WARNING - No schedule given for model serialization, using default 1
2017-08-07 19:04:35,874 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
[src/conv.c:151] err (-127)
[src/conv.c:152] err (-127)
[src/conv.c:153] err (-127)
[src/conv.c:172] err (-1)
[src/conv.c:173] err (-1)
[src/conv.c:174] err (-1)
[src/conv.c:175] err (-1)
[src/conv.c:176] err (-1)
[src/conv.c:177] err (-1)
[src/conv.c:178] err (-1)
[src/conv.c:179] err (-1)
[src/conv.c:180] err (-1)
[src/conv.c:204] err (-127)
[src/conv.c:220] err (-1)
Segmentation fault (core dumped)

Any pointers?

**Comment by rsbhat78** [comment]
Guess this happened because there is no support for MKL. Setting backend to CPU works. Thanks.
