### ISSUE TITLE
Audio level normalization

### ISSUE THREAD

**Issue by bigdatabaracus** [NervanaSystems/deepspeech#52]
Hi, I’m using a custom dataset to train the Deep Speech 2 model in neon. The data set includes audio clips recorded at various audio levels. I’m wondering if normalizing the audio clips in one way or the other, prior to the audio feature extraction steps performed by the aeon, will have a positive impact to the performance of the model. 

In the Deep Speech 2 paper it is reported that the inputs to the network are logspectrograms of power normalized audio clips. Does the aeon pipeline perform this power normalization also by default? If not can you usher me to the right direction on how to implement this kind of normalization? 

Thanks a lot!

**Comment by tyler-nervana** [comment]
Aeon does peak normalization on each audio file prior to feature extraction, so you should be good to go. 

If you want to do [power normalization](https://en.wikipedia.org/wiki/Audio_normalization#Loudness_normalization) you can just normalize the standard deviation of each audio waveform to some common value. If you do this, though, you have to watch out for clipping of the audio when it gets written to disk. Aeon doesn't support this yet, so you'd have to do this beforehand.

**Comment by bigdatabaracus** [comment]
Excellent, thank you very much! Could you link me to the bit of code where the peak normalization is happening in aeon? Is the peak normalized peak value set to 0 dBFS or what is the value of this parameter and can it be tweaked?  

Thanks a lot for the quick answer!

**Comment by tyler-nervana** [comment]
Good questions, and unfortunately I misspoke. Aeon **does not** do any peak normalization. I apologize for that. The most common thing I've seen would be to peak normalize to 0 dBFS. You should be able to do this easily using the [`sox`](http://sox.sourceforge.net/sox.html) command line utility (`sox infile outfile gain −n` seems to work for me)

**Comment by bigdatabaracus** [comment]
Hey, no worries! This is good to know. Thanks a lot for the clear answer on power normalization earlier!

**Comment by tyler-nervana** [comment]
Closing for now. Let us know if you have anymore questions.
