### ISSUE TITLE
'str' object has no attribute 'decode' in Python3

### ISSUE THREAD

**Issue by michalkuligowski** [NervanaSystems/deepspeech#53]
**Steps to reproduce:**

> python train.py --manifest train:/root/librispeech/train-clean-100/train-manifest.csv --manifest val:/root/librispeech/dev-clean/val-manifest.csv -s /root/model_output.prm -i 0 -b gpu -e 1 -z 8 -vvv --save_path /home/lab_idljenk/neon_models/deepspeech/60/model.prm -H 2 --serialize 5

**Actual results:**

> Epoch 0   [Train |████████████████████|  132/132  batches, 586.83 cost, 256.77s]2017-09-10 16:01:00,949 - neon.callbacks.callbacks - INFO - Epoch 0 complete.  Train Cost 599.254822.
> /home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@3/60/deepspeech/speech/sample_proposals_callback.py:73: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   prediction = self.decoder.decode(probs[mu, :, :utt_lens[mu]])
> 
> Traceback (most recent call last):
>   File "train.py", line 145, in <module>
>     cost=cost, callbacks=callbacks)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@3/60/neon/models/model.py", line 185, in fit
>     callbacks.on_epoch_end(self.epoch_index)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@3/60/neon/callbacks/callbacks.py", line 307, in on_epoch_end
>     c.on_epoch_end(self.callback_data, self.model(), epoch)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@3/60/deepspeech/speech/sample_proposals_callback.py", line 87, in on_epoch_end
>     ', Target: ' + (disp_target.decode('ISO-8859-1')).encode('utf-8'))
> **AttributeError: 'str' object has no attribute 'decode'**

**Configuration:**

> gpu 1080ti
> Ubuntu 14.04
> Python 3.4.3

**Comment by tyler-nervana** [comment]
This should be fixed once #54 goes in. Thanks for alerting us to it.
