### ISSUE TITLE
slice indices must be integers or None or have an __index__ method 

### ISSUE THREAD

**Issue by michalkuligowski** [NervanaSystems/deepspeech#55]
branch - tsocha/support_for_new_aeon
python 3
Ubuntu 14.04
backend GPU

http://10.91.54.11:8080/view/Development/job/Dev_tszulisx_neon_aeon_smoke/225/console

> Epoch 0   [Train |████████████████████|  132/132  batches, 584.55 cost, 256.39s]2017-09-20 12:05:21,783 - neon.callbacks.callbacks - INFO - Epoch 0 complete.  Train Cost 629.358948.
> 
> Traceback (most recent call last):
>   File "train.py", line 145, in <module>
>     cost=cost, callbacks=callbacks)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@2/225/neon/models/model.py", line 185, in fit
>     callbacks.on_epoch_end(self.epoch_index)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@2/225/neon/callbacks/callbacks.py", line 307, in on_epoch_end
>     c.on_epoch_end(self.callback_data, self.model(), epoch)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@2/225/deepspeech/speech/sample_proposals_callback.py", line 85, in on_epoch_end
>     cer, disp_proposal, disp_target = self.get_wer(model, self.eval_set)
>   File "/home/lab_idljenk/workspace/Dev_tszulisx_neon_aeon_smoke@2/225/deepspeech/speech/sample_proposals_callback.py", line 73, in get_wer
>     prediction = self.decoder.decode(probs[mu, :, :utt_lens[mu]])
> TypeError: slice indices must be integers or None or have an __index__ method

**Comment by tyler-nervana** [comment]
This was fixed in #54. Let us know if you still have troubles after pulling down those changes.
