### ISSUE TITLE
' assert status is 0, "Warp-CTC run failed" ' - CUDA 8

### ISSUE THREAD

**Issue by krishdeeplearning** [NervanaSystems/deepspeech#7]
Hi,

I am getting the above error while training using CUDA 8.  The status code received is 3. Adding
`set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_60,code=sm_60")`
in the CMakelists fixes it. Is this error something that needs to be fixed?

Thanks!

**Comment by tyler-nervana** [comment]
Thanks for reporting this. This is related to https://github.com/baidu-research/warp-ctc/pull/48. There they raised some concerns about adding too many architectures, but for now your fix should be fine.

**Comment by tyler-nervana** [comment]
Fixed by #31
